MotChallenge2DBox
MPNTrack
Traceback (most recent call last):
  File "/run/netsop/u/home-sam/home/sfiorill/Desktop/Salvo/code/TrackEval/trackeval/eval.py", line 113, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/netsop/u/home-sam/home/sfiorill/Desktop/Salvo/code/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "/run/netsop/u/home-sam/home/sfiorill/Desktop/Salvo/code/TrackEval/trackeval/eval.py", line 218, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/netsop/u/home-sam/home/sfiorill/Desktop/Salvo/code/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "/run/netsop/u/home-sam/home/sfiorill/Desktop/Salvo/code/TrackEval/trackeval/datasets/_base_dataset.py", line 92, in get_raw_seq_data
    raw_gt_data = self._load_raw_file(tracker, seq, is_gt=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/netsop/u/home-sam/home/sfiorill/Desktop/Salvo/code/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 228, in _load_raw_file
    time_data = np.asarray(read_data[time_key], dtype=np.float)
                                                      ^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?





MotChallenge2DBox
MPNTrack
Traceback (most recent call last):
  File "/run/netsop/u/home-sam/home/sfiorill/Desktop/Salvo/code/TrackEval/trackeval/eval.py", line 113, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/netsop/u/home-sam/home/sfiorill/Desktop/Salvo/code/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "/run/netsop/u/home-sam/home/sfiorill/Desktop/Salvo/code/TrackEval/trackeval/eval.py", line 218, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/netsop/u/home-sam/home/sfiorill/Desktop/Salvo/code/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "/run/netsop/u/home-sam/home/sfiorill/Desktop/Salvo/code/TrackEval/trackeval/datasets/_base_dataset.py", line 92, in get_raw_seq_data
    raw_gt_data = self._load_raw_file(tracker, seq, is_gt=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/netsop/u/home-sam/home/sfiorill/Desktop/Salvo/code/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 228, in _load_raw_file
    time_data = np.asarray(read_data[time_key], dtype=np.float)
                                                      ^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?





MotChallenge2DBox
MPNTrack
Traceback (most recent call last):
  File "/run/netsop/u/home-sam/home/sfiorill/Desktop/Salvo/code/TrackEval/trackeval/eval.py", line 180, in evaluate
    metric.plot_single_tracker_results(table_res, tracker_display_name, c_cls,
  File "/run/netsop/u/home-sam/home/sfiorill/Desktop/Salvo/code/TrackEval/trackeval/metrics/hota.py", line 185, in plot_single_tracker_results
    from matplotlib import pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'





MotChallenge2DBox
MPNTrack
Traceback (most recent call last):
  File "/run/netsop/u/home-sam/home/sfiorill/Desktop/Salvo/code/TrackEval/trackeval/eval.py", line 180, in evaluate
    metric.plot_single_tracker_results(table_res, tracker_display_name, c_cls,
  File "/run/netsop/u/home-sam/home/sfiorill/Desktop/Salvo/code/TrackEval/trackeval/metrics/hota.py", line 185, in plot_single_tracker_results
    from matplotlib import pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'





MotChallenge2DBox
last_execution
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/sfiorill/miniconda3/envs/testenv/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/sfiorill/miniconda3/envs/testenv/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/_timing.py", line 64, in wrap
    return f(*args, **kw)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/eval.py", line 218, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/_timing.py", line 64, in wrap
    return f(*args, **kw)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/datasets/_base_dataset.py", line 92, in get_raw_seq_data
    raw_gt_data = self._load_raw_file(tracker, seq, is_gt=True)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 228, in _load_raw_file
    time_data = np.asarray(read_data[time_key], dtype=np.float)
  File "/home/sfiorill/miniconda3/envs/testenv/lib/python3.9/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/eval.py", line 102, in evaluate
    results = pool.map(_eval_sequence, seq_list)
  File "/home/sfiorill/miniconda3/envs/testenv/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/sfiorill/miniconda3/envs/testenv/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations





MotChallenge2DBox
last_execution
Traceback (most recent call last):
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/eval.py", line 113, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/eval.py", line 218, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/datasets/_base_dataset.py", line 92, in get_raw_seq_data
    raw_gt_data = self._load_raw_file(tracker, seq, is_gt=True)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 228, in _load_raw_file
    time_data = np.asarray(read_data[time_key], dtype=np.float)
  File "/home/sfiorill/miniconda3/envs/testenv/lib/python3.9/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations





MotChallenge2DBox
last_execution
Traceback (most recent call last):
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/eval.py", line 113, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/eval.py", line 218, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/datasets/_base_dataset.py", line 92, in get_raw_seq_data
    raw_gt_data = self._load_raw_file(tracker, seq, is_gt=True)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 228, in _load_raw_file
    time_data = np.asarray(read_data[time_key], dtype=np.float)
  File "/home/sfiorill/miniconda3/envs/testenv/lib/python3.9/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations





MotChallenge2DBox
last_execution
Traceback (most recent call last):
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/eval.py", line 113, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/eval.py", line 222, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 359, in get_preprocessed_seq_data
    to_remove_tracker = np.array([], np.int)
  File "/home/sfiorill/miniconda3/envs/testenv/lib/python3.9/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations





MotChallenge2DBox
last_execution
Traceback (most recent call last):
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/eval.py", line 113, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/eval.py", line 222, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 413, in get_preprocessed_seq_data
    data['gt_ids'][t] = gt_id_map[data['gt_ids'][t]].astype(np.int)
  File "/home/sfiorill/miniconda3/envs/testenv/lib/python3.9/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations





MotChallenge2DBox
last_execution
Traceback (most recent call last):
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/eval.py", line 113, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/eval.py", line 224, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/metrics/hota.py", line 31, in eval_sequence
    res[field] = np.zeros((len(self.array_labels)), dtype=np.float)
  File "/home/sfiorill/miniconda3/envs/testenv/lib/python3.9/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations





MotChallenge2DBox
last_execution
Traceback (most recent call last):
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/eval.py", line 113, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/eval.py", line 224, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/metrics/hota.py", line 31, in eval_sequence
    res[field] = np.zeros((len(self.array_labels)), dtype=float)
  File "/home/sfiorill/miniconda3/envs/testenv/lib/python3.9/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations





MotChallenge2DBox
last_execution
Traceback (most recent call last):
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/eval.py", line 113, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/eval.py", line 224, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/metrics/identity.py", line 83, in eval_sequence
    res['IDFN'] = fn_mat[match_rows, match_cols].sum().astype(np.int)
  File "/home/sfiorill/miniconda3/envs/testenv/lib/python3.9/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations





MotChallenge2DBox
last_execution
Traceback (most recent call last):
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/eval.py", line 113, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/eval.py", line 224, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/sfiorill/ReTrack/TrackEval/trackeval/metrics/identity.py", line 83, in eval_sequence
    res['IDFN'] = fn_mat[match_rows, match_cols].sum().astype(int)
  File "/home/sfiorill/miniconda3/envs/testenv/lib/python3.9/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations





